[package]
edition = "2021"
name = "dos-cp"
version = "0.0.3"
rust-version = "1.67"
authors = ["warlock <internalmike@gmail.com>"]
description = "DOS code pages."
readme = "README.md"
documentation = "https://docs.rs/dos-cp/"
keywords = ["codepage", "dos", "oem", "unicode", "encoding"]
categories = ["encoding", "no-std"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/A1-Triard/dos-cp"

[workspace]
exclude = [
    "generator",
    "ensure_no_std",
    "tools",
]

[badges]
maintenance = { status = "actively-developed" }
